#
#
# APR_FOUND
# APR_INCLUDE_PATH
# APR_LIBRARY
#
 

IF(WIN32)
	# TODO !
ELSE(WIN32)
		
	FIND_PATH(APR_INCLUDE_DIR apr.h
		/usr/local/include/apr-1
		/usr/local/include/apr-1.0
		/usr/include/apr-1
		/usr/include/apr-1.0
	)
	
	FIND_LIBRARY(APR_LIBRARY
  		NAMES 
  			apr-1
  		PATHS
  			/usr/lib
  			/usr/lib64
  			/usr/local/lib
  			/usr/local/lib64
  	)
ENDIF(WIN32)

IF (APR_LIBRARY AND APR_INCLUDE_DIR)
    SET(APR_LIBRARIES ${APR_LIBRARY})
    SET(APR_FOUND "YES")
ELSE (APR_LIBRARY AND APR_INCLUDE_DIR)
  SET(APR_FOUND "NO")
ENDIF (APR_LIBRARY AND APR_INCLUDE_DIR)

IF (APR_FOUND)
   IF (NOT APR_FIND_QUIETLY)
      MESSAGE(STATUS "Found APR: ${APR_LIBRARIES}")
   ENDIF (NOT APR_FIND_QUIETLY)
ELSE (APR_FOUND)
   IF (APR_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find APR library")
   ENDIF (APR_FIND_REQUIRED)
ENDIF (APR_FOUND)

MARK_AS_ADVANCED(
  APR_LIBRARY
  APR_INCLUDE_DIR
  )

# APR UTILS  

IF(WIN32)
	# TODO !
ELSE(WIN32)
		
	FIND_PATH(APRUTIL_INCLUDE_DIR apu.h
		/usr/local/include/apr-1
		/usr/local/include/apr-1.0
		/usr/include/apr-1
		/usr/include/apr-1.0
	)
	
	FIND_LIBRARY(APRUTIL_LIBRARY
  		NAMES 
  			aprutil-1
  		PATHS
  			/usr/lib
  			/usr/lib64
  			/usr/local/lib
  			/usr/local/lib64
  	)
ENDIF(WIN32)


IF (APRUTIL_LIBRARY AND APRUTIL_INCLUDE_DIR)
    SET(APRUTIL_LIBRARIES ${APRUTIL_LIBRARY})
    SET(APRUTIL_FOUND "YES")
ELSE (APRUTIL_LIBRARY AND APRUTIL_INCLUDE_DIR)
  SET(APRUTIL_FOUND "NO")
ENDIF (APRUTIL_LIBRARY AND APRUTIL_INCLUDE_DIR)


IF (APRUTIL_FOUND)
   IF (NOT APRUTIL_FIND_QUIETLY)
      MESSAGE(STATUS "Found APRUTIL: ${APRUTIL_LIBRARIES}")
   ENDIF (NOT APRUTIL_FIND_QUIETLY)
ELSE (APRUTIL_FOUND)
   IF (APRUTIL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find APRUTIL library")
   ENDIF (APRUTIL_FIND_REQUIRED)
ENDIF (APRUTIL_FOUND)

MARK_AS_ADVANCED(
  APRUTIL_LIBRARY
  APRUTIL_INCLUDE_DIR
  )