#
#
# FTGL_FOUND
# FTGL_INCLUDE_PATH
# FTGL_LIBRARY
#
 

IF(WIN32)
	# TODO !
ELSE(WIN32)
		
	# Look for the header file.	
	FIND_PATH(FTGL_INCLUDE_DIR FTGL/ftgl.h
		/usr/local/include/
		/usr/include/
	)
	
	FIND_LIBRARY(FTGL_LIBRARY
  		NAMES 
  			ftgl
  		PATHS
  			/usr/lib
  			/usr/lib64
  			/usr/local/lib
  			/usr/local/lib64
  	)
ENDIF(WIN32)

IF (FTGL_LIBRARY AND FTGL_INCLUDE_DIR)
    SET(FTGL_LIBRARIES ${FTGL_LIBRARY})
    SET(FTGL_FOUND "YES")
ELSE (FTGL_LIBRARY AND FTGL_INCLUDE_DIR)
  SET(FTGL_FOUND "NO")
ENDIF (FTGL_LIBRARY AND FTGL_INCLUDE_DIR)

IF (FTGL_FOUND)
   IF (NOT FTGL_FIND_QUIETLY)
      MESSAGE(STATUS "Found FTGL: ${FTGL_LIBRARIES}")
   ENDIF (NOT FTGL_FIND_QUIETLY)
ELSE (FTGL_FOUND)
   IF (FTGL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FTGL library")
   ENDIF (FTGL_FIND_REQUIRED)
ENDIF (FTGL_FOUND)

MARK_AS_ADVANCED(
  FTGL_LIBRARY
  FTGL_INCLUDE_DIR
  )
 